runtime: python312
service: api
entrypoint: gunicorn -w 2 -b :$PORT -k uvicorn.workers.UvicornWorker app:parkingbot
instance_class: F1
default_expiration: "30s"
automatic_scaling:
    max_concurrent_requests: 20
    max_instances: 1
    max_idle_instances: 1
app_engine_apis: true
